### ISSUE TITLE
Some pages should be excluded

### ISSUE THREAD

**Issue by dequeued0** [DenverCoder1/unedit-for-reddit#61]
The script puts (non-working) links on some pages where they don't make sense. For example, viewing the moderation log of a subreddit with no recent moderator actions, it will add a red "Show original" link that doesn't work.

I believe these @match and @exclude lines will exclude most pages that aren't submission/comment listings.

```
// @exclude      https://*.reddit.com/*/about/banned*
// @exclude      https://*.reddit.com/*/about/contributors*
// @exclude      https://*.reddit.com/*/about/edit*
// @exclude      https://*.reddit.com/*/about/flair*
// @exclude      https://*.reddit.com/*/about/log*
// @exclude      https://*.reddit.com/*/about/moderators*
// @exclude      https://*.reddit.com/*/about/muted*
// @exclude      https://*.reddit.com/*/about/rules*
// @exclude      https://*.reddit.com/*/about/stylesheet*
// @exclude      https://*.reddit.com/*/about/traffic*
// @exclude      https://*.reddit.com/*/wiki/*
// @exclude      https://mod.reddit.com/*
// @match        https://*.reddit.com/me/f/*
// @match        https://*.reddit.com/message/*
// @match        https://*.reddit.com/r/*
// @match        https://*.reddit.com/user/*
```

The reason there are multiple `/about/` lines rather than a single one is because there are a number of listing pages under /about/ for a subreddit where unedit is definitely wanted.

`/message/*` is included because while private messages cannot be edited, messages does include comment replies and username mentions in comments, both of which can be edited.

I don't believe lines are needed for https://reddit.com/ because that seems to always redirect to https://www.reddit.com/ now.

**Comment by dequeued0** [comment]
> This looks good assuming it's tested.

I've been running with those lines in replacement of the original lines for the last two weeks and it works well.

**Comment by dequeued0** [comment]
I've added one line for the front page itself:

```
// @match        https://*.reddit.com/
```

My full set of `@match` and `@exclude` lines is now:

```
// @exclude      https://*.reddit.com/*/about/banned*
// @exclude      https://*.reddit.com/*/about/contributors*
// @exclude      https://*.reddit.com/*/about/edit*
// @exclude      https://*.reddit.com/*/about/flair*
// @exclude      https://*.reddit.com/*/about/log*
// @exclude      https://*.reddit.com/*/about/moderators*
// @exclude      https://*.reddit.com/*/about/muted*
// @exclude      https://*.reddit.com/*/about/rules*
// @exclude      https://*.reddit.com/*/about/stylesheet*
// @exclude      https://*.reddit.com/*/about/traffic*
// @exclude      https://*.reddit.com/*/wiki/*
// @exclude      https://mod.reddit.com/*
// @match        https://*.reddit.com/
// @match        https://*.reddit.com/me/f/*
// @match        https://*.reddit.com/message/*
// @match        https://*.reddit.com/r/*
// @match        https://*.reddit.com/user/*
```

**Comment by DenverCoder1** [comment]
Thanks for the contribution, I have merged a fix
