### ISSUE TITLE
[Feature Request] Support for .compact Reddit

### ISSUE THREAD

**Issue by LOuroboros** [DenverCoder1/unedit-for-reddit#64]
Hello. I imagine there's a good chance this'll be rejected because it only adds more development burden, but I figured it was worth bringing up anyway.

So, I personally use "Compact Reddit". That's an extremely basic design that Reddit uses when you append the `.compact` string at the end of any Reddit URL. I like it because it has barely any bloat or wasted space. It feels pretty comfy, at least to me.

However, this addon/userscript doesn't really work with that design, which means that whenever I want it to show me a deleted post, I need to go back to the Old design of Reddit *(though I imagine the redesign works too? Didn't try since I'm not interested.)* which does contain the "Show Original" button.

What I'm trying to get at is that it would be pretty cool if the addon could be made compatible with Compact Reddit.

Ex:
![firefox_20221104_093635998](https://user-images.githubusercontent.com/4485172/199974665-04d24e52-55fa-4755-ba27-dde873c6ecf6.png)
![Untitled](https://user-images.githubusercontent.com/4485172/199974668-f9e56ed0-bf03-4ede-ad96-af646dbcdf94.png)

**Comment by DenverCoder1** [comment]
It seems that .compact Reddit doesn't mark edited comments, but I was still able to get it to show the links on [deleted] and [removed] posts and comments, and where the author is not shown.

**Comment by LOuroboros** [comment]
Oh wow, thank you so much! It's working beautifully 😃 !

![firefox_20221104_145621303](https://user-images.githubusercontent.com/4485172/200043849-3104b116-e010-4c5e-b638-8ae0d4937707.png)
