### ISSUE TITLE
Fetch failed

### ISSUE THREAD

**Issue by teisseire117** [DenverCoder1/unedit-for-reddit#68]
Hi,

It's been a few days that the script returns that error.
Here is the console logs : 
![14hfbDC](https://user-images.githubusercontent.com/43145883/207914201-f3e72f0e-cfb2-4675-b909-c4aa929f1a1e.png)

It seems that the format for the URL format is not accepted by Pushshift

**Comment by teisseire117** [comment]
Closing this as it seems like an error from Pushshift and not your tool

**Comment by DenverCoder1** [comment]
Yeah, Pushshift is migrating servers so things have been a bit broken on their end for a few days

The Pushshift Data API is undergoing changes as [announced here](https://old.reddit.com/r/pushshift/comments/zhzaea/the_day_has_finally_arrived_pushshift_api_move/). There is also an update [here](https://old.reddit.com/r/pushshift/comments/zk1jyw/link_id_signed_integer_overflow_bugs_in_pushshift/izxv6vg/) and [here](https://www.reddit.com/r/pushshift/comments/zkggt0/update_on_colo_switchover_bug_fixes_reindexing/). Checking [r/pushshift](https://www.reddit.com/r/pushshift) for updates is recommended.

**Comment by Berzerker** [comment]
Just for my info, is this going to require any updates from you once they've addressed all the issues or should it all just start working again?

**Comment by Berzerker** [comment]
I see. I'm still getting "fetch failed" for basically all of my requests, I'm guess I should open a new ticket for this, though.
