### ISSUE TITLE
Unable to fetch any results

### ISSUE THREAD

**Issue by Berzerker** [DenverCoder1/unedit-for-reddit#72]
Not sure if this is still a pushshift issue at this point, I'm only aware that submissions before 11/3/22 are unable to be fetched yet since they haven't loaded in the old data, but I'm unable to fetch anything even recently as well.

Please close this if this is still a PS issue, but afaik your app was already updated to support it, so not sure if there's something else going on.

Thanks!

**Comment by DenverCoder1** [comment]
Do you have specific links that you tried. It seems to be working for me with the latest version, but it seems slower than usual.

**Comment by Berzerker** [comment]
https://old.reddit.com/r/homelab/comments/zwlurj/so_this_is_how_it_feels_like_retiring_at_age_75/j1y5wjz/ Here's one that isn't working for me.

I just get "fetch failed (this is likely a pushshift API issue)" error when trying "show original"

**Comment by DenverCoder1** [comment]
It took about 20 seconds but it loaded for me.

Are there any specific error messages in the console logs?

![image](https://user-images.githubusercontent.com/20955511/210020941-b15b80f9-be91-4463-ba5f-287559d81de7.png)

**Comment by Berzerker** [comment]
I noticed it did seem to try and "load" for quite a while, but did end up failing for me, I see the following in the console logs

![image](https://user-images.githubusercontent.com/448708/210086538-be1935d6-c29b-4886-ba24-361f7f3f20e2.png)

**Comment by DenverCoder1** [comment]
It would appear the pushshift API is returning something that's not JSON.

Do you happen to have the response it returned?

You can usually get it in the Network tab if it's open while making the request.

**Comment by Berzerker** [comment]
Unfortunately, nothing really shows up in the network tab both during the page loading and after trying the fetch.
![image](https://user-images.githubusercontent.com/448708/210088790-97cd8eab-9316-4f6d-912b-511fd3ef9202.png)

**Comment by DenverCoder1** [comment]
It seems like the issue might be a pushshift not responding to the request, it showed a cloudflare 524 error when I tried accessing the link directly

https://api.pushshift.io/reddit/search/comment/?ids=t1_j1y5wjz

**Comment by Berzerker** [comment]
Yeah seems like it. Perhaps stuff is being moved around/loaded in. I'll let it sit for another few weeks and come back if I'm seeing anything different.

Thanks!
