### ISSUE TITLE
Not working on firefox

### ISSUE THREAD

**Issue by C0deTalker** [DenverCoder1/unedit-for-reddit#76]
Hello,

This extension hasn't worked for a while on firefox for me, both on my home and work computers. I feel like it did work in firefox at some point. It just says "not found" on everything. I can see those same comments with the chrome extension. I tried with every extension disabled except this one.

**Comment by DenverCoder1** [comment]
It appears to be a missing permissions issue in the latest version of Firefox. [Firefox 109.0](https://www.mozilla.org/en-US/firefox/109.0/releasenotes/) seems to restrict certain data access features that were previously available. It also supports Manifest v3 now and it seems that with manifest v3, you can get it to work by enabling the permission to access data on Reddit.

I'll see what I can do to put out an update soon.

**Comment by DenverCoder1** [comment]
I adjusted the permissions to get it to work while still keeping manifest v2 for the time being (v3 seems to be a bit buggy at the moment)

Let me know if updating the extension to 3.16.2 works for you.

**Comment by C0deTalker** [comment]
It's working now. Thanks!
