### ISSUE TITLE
Load comments removed by the admins

### ISSUE THREAD

**Issue by Watchful1** [DenverCoder1/unedit-for-reddit#82]
If a comment is removed by the reddit admins, the content is replaced with "[ Removed by Reddit ]" and the option to load the removed comment isn't present.

**Comment by DenverCoder1** [comment]
Do you have an example of a link where this can be seen?

**Comment by Watchful1** [comment]
Unfortunately all the examples I have are from a subreddit I mod so that's the only reason I can see them. Here's one

https://www.reddit.com/r/Competitiveoverwatch/comments/10kzy6u/streamer_eeveea_confirms_that_a_large_text_doc_of/j5twuit/

but I think it will just be blank for you. Here's the full json of the comment

```
{
"author_flair_background_color": null,
"subreddit_id": "t5_34fcy",
"approved_at_utc": null,
"author_is_blocked": false,
"comment_type": null,
"awarders": [],
"mod_reason_by": null,
"banned_by": true,
"author_flair_type": "text",
"total_awards_received": 0,
"subreddit": "Competitiveoverwatch",
"author_flair_template_id": null,
"distinguished": null,
"likes": null,
"replies": "",
"user_reports": [],
"ban_note": "confirm spam",
"saved": false,
"id": "j5twuit",
"banned_at_utc": 1674660346,
"mod_reason_title": null,
"gilded": 0,
"archived": false,
"collapsed_reason_code": null,
"no_follow": true,
"spam": false,
"can_mod_post": true,
"send_replies": true,
"parent_id": "t3_10kzy6u",
"score": 0,
"author_fullname": "t2_vemnaih0",
"editable": false,
"approved_by": null,
"mod_note": null,
"all_awardings": [],
"body": "[ Removed by Reddit ]",
"edited": false,
"gildings": {},
"downs": 0,
"author_flair_css_class": null,
"name": "t1_j5twuit",
"is_submitter": false,
"collapsed": false,
"author_flair_richtext": [],
"author_patreon_flair": false,
"collapsed_reason": null,
"removal_reason": "legal",
"user_reports_dismissed": [
[
"Threatening, harassing, or inciting violence",
1,
false,
true
]
],
"link_id": "t3_10kzy6u",
"associated_award": null,
"stickied": false,
"author_premium": false,
"can_gild": true,
"top_awarded_type": null,
"unrepliable_reason": null,
"approved": false,
"author_flair_text_color": null,
"treatment_tags": [],
"score_hidden": false,
"permalink": "[/r/Competitiveoverwatch/comments/10kzy6u/streamer_eeveea_confirms_that_a_large_text_doc_of/j5twuit/](https://www.reddit.com/r/Competitiveoverwatch/comments/10kzy6u/streamer_eeveea_confirms_that_a_large_text_doc_of/j5twuit/)",
"subreddit_type": "public",
"locked": false,
"report_reasons": [],
"created": 1674660238,
"author_flair_text": null,
"removed": false,
"author": "Formal-Spare-5106",
"created_utc": 1674660238,
"subreddit_name_prefixed": "r/Competitiveoverwatch",
"controversiality": 0,
"depth": 0,
"ignore_reports": false,
"collapsed_because_crowd_control": null,
"mod_reports": [],
"body_html": "&lt;div class=\"md\"&gt;&lt;p&gt;[ Removed by Reddit ]&lt;/p&gt;\n&lt;/div&gt;",
"num_reports": -1,
"ups": 0
}
```

It looks [like this](https://i.imgur.com/wDrxjc7.png) in old reddit [and this](https://i.imgur.com/eRB3MPk.png) in new reddit.

**Comment by DenverCoder1** [comment]
I currently have it so that missing comments will show the link below, for example, on this post it looks like this:

![image](https://user-images.githubusercontent.com/20955511/214932087-ca3a9a6e-193e-4111-ac83-1d1f79c7b43a.png)

I have not tested it in moderation mode, so that explains why.

Do note that, if Reddit removes a comment immediately then there is no way for it have been archived since the text was never available via the API, so it would end up showing something like [removed] which isn't very useful.

![image](https://user-images.githubusercontent.com/20955511/214932420-6752cd37-00af-458c-9cd8-b5abccf321a2.png)

I can try to support it, but as shown, it seems like 99%+ of the time the information won't be useful.

**Comment by Watchful1** [comment]
Here's another example that it looks like pushshift does have

https://www.reddit.com/r/Competitiveoverwatch/comments/10kzy6u/streamer_eeveea_confirms_that_a_large_text_doc_of/j5vpz6x/

**Comment by Watchful1** [comment]
In most of these cases we notice the admins removed a comment, but we want to go back and look it up to see if it warrants an additional ban on top of whatever the admins did.

Some of them are automated, but I'm fairly sure a decent percent are manual removal later on that would be archived by pushshift.

**Comment by DenverCoder1** [comment]
> Here's another example that it looks like pushshift does have
> 
> [reddit.com/r/Competitiveoverwatch/comments/10kzy6u/streamer_eeveea_confirms_that_a_large_text_doc_of/j5vpz6x](https://www.reddit.com/r/Competitiveoverwatch/comments/10kzy6u/streamer_eeveea_confirms_that_a_large_text_doc_of/j5vpz6x/)

These ones appear to be removed by Moderator which also seems to work when not logged in or not a moderator

![image](https://user-images.githubusercontent.com/20955511/214934288-09ae1c2e-e894-426e-b65c-0b2092b0f4c4.png)

What does it look like for you?

**Comment by Watchful1** [comment]
![image](https://user-images.githubusercontent.com/1574415/214934518-a7698f25-e1d8-4978-b65e-c24c39d370b6.png)

**Comment by Watchful1** [comment]
I installed from the chrome web store, but I'm happy to manually install to help test.

**Comment by DenverCoder1** [comment]
I created this branch for the feature

https://github.com/DenverCoder1/unedit-for-reddit/tree/feat-support-Removed-by-Reddit%5D-for-moderator-view

If you could let me know if it is working or not, that would help. You can install with a userscript method or load unpacked (the readme has a brief explanation all the different methods)

**Comment by Watchful1** [comment]
Will do, unfortunately it'll have to wait till I'm off work, but I'll get back to you then.

**Comment by Watchful1** [comment]
![image](https://user-images.githubusercontent.com/1574415/214988600-5957fa4b-7313-4c0b-a103-bffdcde2aa3f.png)
 
It works, thanks!
