### ISSUE TITLE
Extract permalinks for delated messages

### ISSUE THREAD

**Issue by strayr** [DenverCoder1/unedit-for-reddit#87]
IS there a way to extract the reddit permalinks from removed content?

I would like to be able to point reddit addmins at the content showing up as [removed by moderator] as it seems AEO is acting on the wrong stuff. 

Example: Posts in yellow here, where you can show me the content. I've censored this to protect all concerned, I'm a moderator on a big sub and we're having big problems with AEO _not getting it_
https://imgur.com/mKceO9Y

**Comment by DenverCoder1** [comment]
You should be able to get the link by clicking the timestamp eg. "2 days ago" or from the "Share menu"

This is the case without running Unedit for Reddit as well.

If you show the original with Unedit for Reddit, the timestamp link at the bottom of the yellow box also is a permalink to the post/comment.
