### ISSUE TITLE
Extension is causing flairs to disappear on /r/NBA

### ISSUE THREAD

**Issue by pzrd** [DenverCoder1/unedit-for-reddit#88]
So today I decided to finally find out why team flairs disappear on /r/NBA and I've narrowed it down to this extension. With the extension enabled and on old reddit, go to /r/NBA and you'll see flairs show up for a second, then the page does a mini reset by itself and then most flairs (weirdly neutral flairs like the NBA logo itself are unaffected) are gone until you manually refresh. 

It only occurs on /r/NBA and none of the other sports subs I have tried like /r/soccer /r/NFL /r/hockey and /r/baseball. I've had this problem for about a year but never bothered to find the cause of it, but after clearing my cache and reenabling every extension one-by-one, I'm pretty sure this is the cause. 

Think it can be fixed?
![SS_130223-162840](https://user-images.githubusercontent.com/82322348/218516700-c0cf9fdd-5bb4-45f7-b528-75c0b0b80c06.png)
![SS_130223-163159](https://user-images.githubusercontent.com/82322348/218516703-d995077f-b665-4f24-8d92-76af90a7b41e.png)

**Comment by DenverCoder1** [comment]
Looks like it's caused by their custom CSS expecting flair full class names to *end* with "1", meaning if additional classes are added, their selector will not

In r/NBA custom css: `*[class^="flair flair"][class$="1"]:before { ... }`

**Comment by pzrd** [comment]
Interesting, thank you for taking a look. Can you walk me through adding that line to the custom CSS via either RES or TamperMonkey? I tried adding it as a CSS snippet in RES but it didn't work. 
![SS_130223-180355](https://user-images.githubusercontent.com/82322348/218537160-df3eb21a-6207-414d-9b05-3451171a2b9e.png)

**Comment by DenverCoder1** [comment]
That's the problematic line, if you want to make an override style for the subreddit, you could add something like

```css
*[class^="flair flair"][class*="1 "]:before {
    background-position-x:  0;
}
```

**Comment by DenverCoder1** [comment]
The extension (v. 3.16.3+) will now not add any classes to flair elements, so the issue is resolved
