### ISSUE TITLE
[Safari v16.4, Userscripts v4.4.0] "fetch failed" error 

### ISSUE THREAD

**Issue by v7rzlhb3xg** [DenverCoder1/unedit-for-reddit#95]
Hi, I've been getting the "fetch failed" error recently when trying to show original comments or posts. Running macOS Ventura v13.3.1, Safari v16.4, Userscripts v4.4.0. I've tried reinstalling the script, my userscript manager, and removing all other extensions in case there was a conflict, without any success. Here's the output of the dev console when I get the error:

<img width="1464" alt="Screenshot 2023-04-18 at 7 51 12 PM" src="https://user-images.githubusercontent.com/18043024/232929680-54711a40-3bee-4338-a98e-ef57e191ad5f.png">

Let me know if you need any other information!

**Comment by DenverCoder1** [comment]
It is most likely a temporary issue with the Pushshift API.

The URL failed to load at https://api.pushshift.io/reddit/search/submission?ids=t3_12qq004&fields=selftext,author,id,created_utc,permalink

I have tried fetching the same post and it is working for me.

![image](https://user-images.githubusercontent.com/20955511/232988004-288ee4c6-844f-4ba4-87c1-e3eed74ddbfd.png)
