### ISSUE TITLE
Will this be updated to support the new pushshift api credentials?

### ISSUE THREAD

**Issue by goryramsy** [DenverCoder1/unedit-for-reddit#98]
Pushshift is back online (https://old.reddit.com/r/pushshift/comments/14ei799/pushshift_live_again_and_how_moderators_can/) and has been backfilled with content. The new update requires authentication, (https://api.pushshift.io/docs#), through cURL  headers. 

One tool, https://adhesivecheese.github.io/chearch/, has already been updated with the access token functionality. Will unedit-for-reddit be updated as well?

**Comment by DenverCoder1** [comment]
I don't have access to the API so I can't fully test the code, though I think it should work.

Are you able to load the code from the PR by any chance to test it?

**Comment by goryramsy** [comment]
Reddit itself is down right now, but I will when I can, thanks! Also, the new authentication expires every 24 hours, so I'd be fine with sharing a temporary key with you so you can test.

**Comment by goryramsy** [comment]
Tested and is working! Confirmed with loading unpacked chrome extension on chromium 114.0.5735.133. My offer of sharing an api key for testing purposes still stands.

**Comment by DenverCoder1** [comment]
Thanks for sharing the API key, it was useful for testing and fixing some issues. It was working well in Chrome and the Userscript version but there were some issues with the headers not getting passed in Firefox. I was able to make a workaround for Firefox (though it is a bit hacky).

Thanks for your help getting this back to being usable. :+1:
